stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/New_Data.csv
    - params.yaml
    - src/preprocess.py
    outs:
    - data/processed/test.pkl
    - data/processed/train.pkl
    - models/preprocessor.pkl
  train:
    cmd: python src/train.py
    deps:
    - data/processed/test.pkl
    - data/processed/train.pkl
    - params.yaml
    - src/train.py
    outs:
    - models/best_model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/test.pkl
    - models/best_model.pkl
    - src/evaluate.py
    outs:
    - reports/confusion_matrix.png
    - reports/metrics.json
