data:
  test_size: 0.2
  random_state: 42

models:
  logistic_regression:
    max_iter: 200

  random_forest:
    n_estimators: 100
    max_depth: 6

  xgboost:
    n_estimators: 150
    max_depth: 5
    learning_rate: 0.1